<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Status extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_model');
        $this->load->library('form_validation');
		if (!$this->ion_auth->logged_in())
		{
			redirect('auth/login', 'refresh');
		}else if (!$this->ion_auth->is_admin()) {
			return show_error('You must be an administrator to view this page.');
		}
    }

    public function index()
    {
        $status = $this->Status_model->get_all();

        $data = array(
            'status_data' => $status,
			'controller' => 'Status',
			'uri1' => 'List Status',
			'main_view' => 'status/status_list'
        );

        $this->load->view('template_view', $data);
    }

    public function read($id) 
    {
        $row = $this->Status_model->get_by_id($id);
        if ($row) {
            $data = array(
			'controller' => 'Status',
			'uri1' => 'List Status',
			'main_view' => 'status/status_read',
			
			'id_status' => $row->id_status,
			'status' => $row->status,
	    );
            $this->load->view('template_view', $data);
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('status'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('status/create_action'),
			'controller' => 'Status',
			'uri1' => 'List Status',
			'main_view' => 'status/status_form',
			
			'id_status' => set_value('id_status'),
			'status' => set_value('status'),
	);
        $this->load->view('template_view', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'status' => $this->input->post('status',TRUE),
	    );

            $this->Status_model->insert($data);
            $this->session->set_flashdata('message', 'Data Berhasil Ditambahkan');
            redirect(site_url('status'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Status_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('status/update_action'),
				'controller' => 'Status',
				'uri1' => 'List Status',
				'main_view' => 'status/status_form',
			
			'id_status' => set_value('id_status', $row->id_status),
			'status' => set_value('status', $row->status),
	    );
            $this->load->view('template_view', $data);
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('status'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_status', TRUE));
        } else {
            $data = array(
		'status' => $this->input->post('status',TRUE),
	    );

            $this->Status_model->update($this->input->post('id_status', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Data Berhasil');
            redirect(site_url('status'));
        }
    }
    
    public function delete($id) 
    {
		if ($this->cek_fk($id) != TRUE)
		{
			$row = $this->Status_model->get_by_id($id);
			if ($row) {
				$this->Status_model->delete($id);
				$this->session->set_flashdata('message', 'Data Berhasil Dihapus');
				redirect(site_url('status'));
			} else {
				$this->session->set_flashdata('error', 'Data Tidak Ditemukan');
				redirect(site_url('status'));
			}
		} 
		else
		{
			$this->session->set_flashdata('error', 'Data tidak bisa dihapus karena memiliki koneksi ke data lain');
			redirect(site_url('status'));
		}
    }
	
	public function cek_fk($id)
	{
		$fk = $this->Status_model->get_fk_by_id($id);
		if ($fk > 0)
		{
			return TRUE;
		}
	}

    public function _rules() 
    {
	$this->form_validation->set_rules('status', 'status', 'trim|required');

	$this->form_validation->set_rules('id_status', 'id_status', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    function pdf()
    {
        $data = array(
            'status_data' => $this->Status_model->get_all(),
            'start' => 0
        );
        
        ini_set('memory_limit', '32M');
		$this->load->library('pdfgenerator');
		$psize = 'folio'; //setting kertas
		$orient = 'landscape'; 	//setting orientasi		
 
	    $html = $this->load->view('status/status_pdf', $data, true);
	    
	    $this->pdfgenerator->generate($html,'list Status',$psize,$orient); 
		       
    }

}

/* End of file Status.php */
/* Location: ./application/controllers/Status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-07 03:26:45 */
/* http://harviacode.com */
?>
