<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Periode_laporan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Periode_laporan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $periode_laporan = $this->Periode_laporan_model->get_all();

        $data = array(
            'periode_laporan_data' => $periode_laporan,
			'controller' => 'Periode_laporan',
			'uri1' => 'List Periode_laporan',
			'main_view' => 'periode_laporan/periode_laporan_list'
        );

        $this->load->view('template_view', $data);
    }

    public function read($id) 
    {
        $row = $this->Periode_laporan_model->get_by_id($id);
        if ($row) {
            $data = array(
			'controller' => 'Periode_laporan',
			'uri1' => 'Data Periode_laporan',
			'main_view' => 'periode_laporan/periode_laporan_read',
			
			'id_per_lap' => $row->id_per_lap,
			'tanggal' => $row->tanggal,
	    );
            $this->load->view('template_view', $data);
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('periode_laporan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('periode_laporan/create_action'),
			'controller' => 'Periode_laporan',
			'uri1' => 'Tambah Periode_laporan',
			'main_view' => 'periode_laporan/periode_laporan_form',
			
			'id_per_lap' => set_value('id_per_lap'),
			'tanggal' => set_value('tanggal'),
	);
        $this->load->view('template_view', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'tanggal' => $this->input->post('tanggal',TRUE),
	    );

            $this->Periode_laporan_model->insert($data);
            $this->session->set_flashdata('message', 'Data Berhasil Ditambahkan');
            redirect(site_url('periode_laporan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Periode_laporan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('periode_laporan/update_action'),
				'controller' => 'Periode_laporan',
				'uri1' => 'Update Periode_laporan',
				'main_view' => 'periode_laporan/periode_laporan_form',
			
			'id_per_lap' => set_value('id_per_lap', $row->id_per_lap),
			'tanggal' => set_value('tanggal', $row->tanggal),
	    );
            $this->load->view('template_view', $data);
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('periode_laporan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_per_lap', TRUE));
        } else {
            $data = array(
		'tanggal' => $this->input->post('tanggal',TRUE),
	    );

            $this->Periode_laporan_model->update($this->input->post('id_per_lap', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Data Berhasil');
            redirect(site_url('periode_laporan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Periode_laporan_model->get_by_id($id);

        if ($row) {
            $this->Periode_laporan_model->delete($id);
            $this->session->set_flashdata('message', 'Data Berhasil Dihapus');
            redirect(site_url('periode_laporan'));
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('periode_laporan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('tanggal', 'tanggal', 'trim|required');

	$this->form_validation->set_rules('id_per_lap', 'id_per_lap', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Periode_laporan.php */
/* Location: ./application/controllers/Periode_laporan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-02 09:54:30 */
/* http://harviacode.com */
?>
