<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Real_fisik extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Real_fisik_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $real_fisik = $this->Real_fisik_model->get_all();

        $data = array(
            'real_fisik_data' => $real_fisik,
			'controller' => 'Real_fisik',
			'uri1' => 'List Real_fisik',
			'main_view' => 'real_fisik/real_fisik_list'
        );

        $this->load->view('template_view', $data);
    }

    public function read($id) 
    {
        $row = $this->Real_fisik_model->get_by_id($id);
        if ($row) {
            $data = array(
			'controller' => 'Real_fisik',
			'uri1' => 'Data Real_fisik',
			'main_view' => 'real_fisik/real_fisik_read',
			
			'id_real_fisik' => $row->id_real_fisik,
			'nilai' => $row->nilai,
			'periode' => $row->periode,
			'kegiatan' => $row->kegiatan,
	    );
            $this->load->view('template_view', $data);
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('real_fisik'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('real_fisik/create_action'),
			'controller' => 'Real_fisik',
			'uri1' => 'Tambah Real_fisik',
			'main_view' => 'real_fisik/real_fisik_form',
			
			'id_real_fisik' => set_value('id_real_fisik'),
			'nilai' => set_value('nilai'),
			'periode' => set_value('periode'),
			'kegiatan' => set_value('kegiatan'),
	);
        $this->load->view('template_view', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nilai' => $this->input->post('nilai',TRUE),
		'periode' => $this->input->post('periode',TRUE),
		'kegiatan' => $this->input->post('kegiatan',TRUE),
	    );

            $this->Real_fisik_model->insert($data);
            $this->session->set_flashdata('message', 'Data Berhasil Ditambahkan');
            redirect(site_url('real_fisik'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Real_fisik_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('real_fisik/update_action'),
				'controller' => 'Real_fisik',
				'uri1' => 'Update Real_fisik',
				'main_view' => 'real_fisik/real_fisik_form',
			
			'id_real_fisik' => set_value('id_real_fisik', $row->id_real_fisik),
			'nilai' => set_value('nilai', $row->nilai),
			'periode' => set_value('periode', $row->periode),
			'kegiatan' => set_value('kegiatan', $row->kegiatan),
	    );
            $this->load->view('template_view', $data);
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('real_fisik'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_real_fisik', TRUE));
        } else {
            $data = array(
		'nilai' => $this->input->post('nilai',TRUE),
		'periode' => $this->input->post('periode',TRUE),
		'kegiatan' => $this->input->post('kegiatan',TRUE),
	    );

            $this->Real_fisik_model->update($this->input->post('id_real_fisik', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Data Berhasil');
            redirect(site_url('real_fisik'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Real_fisik_model->get_by_id($id);

        if ($row) {
            $this->Real_fisik_model->delete($id);
            $this->session->set_flashdata('message', 'Data Berhasil Dihapus');
            redirect(site_url('real_fisik'));
        } else {
            $this->session->set_flashdata('message', 'Data Tidak Ditemukan');
            redirect(site_url('real_fisik'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nilai', 'nilai', 'trim|required|numeric');
	$this->form_validation->set_rules('periode', 'periode', 'trim|required');
	$this->form_validation->set_rules('kegiatan', 'kegiatan', 'trim|required');

	$this->form_validation->set_rules('id_real_fisik', 'id_real_fisik', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Real_fisik.php */
/* Location: ./application/controllers/Real_fisik.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-02 09:54:30 */
/* http://harviacode.com */
?>
