<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pekerjaan_model extends CI_Model
{

    public $table = 'pekerjaan';
    public $id = 'id';
    public $order = 'DESC';
	private $db2;

    function __construct()
    {
        parent::__construct();
		    $this->db2 = $this->load->database('db2',TRUE);
    }

    // get all
    function get_all()
    {
      $this->db->select('p.id, p.nama, p.kegiatan, s.nama_skpd, j.nama as jenis, m.nama as metode, p.pagu, p.realisasi');
      $this->db->from('simolek_p.pekerjaan p');
      $this->db->join('simolek.skpd s', 's.id_skpd=p.skpd', 'left');
      $this->db->join('simolek_p.jenis j', 'p.jenis=j.id', 'left');
      $this->db->join('simolek_p.metode m', 'p.metode=m.id', 'left');
      $this->db->order_by('p.id', 'desc');
      return $this->db->get()->result();
        // $this->db2->order_by($this->id, $this->order);
        // return $this->db2->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
      $this->db->select('p.id as id_p, p.nama, p.kegiatan, s.id_skpd, s.nama_skpd, j.id as id_j, j.nama as jenis, m.id as id_m, m.nama as metode, p.pagu, p.realisasi');
      $this->db->from('simolek_p.pekerjaan p');
      $this->db->join('simolek.skpd s', 'p.skpd=s.id_skpd', 'left');
      $this->db->join('simolek_p.jenis j', 'p.jenis=j.id', 'left');
      $this->db->join('simolek_p.metode m', 'p.metode=m.id', 'left');
      $this->db->where('p.id', $id);
      return $this->db->get('simolek_p.pekerjaan')->row();
    }

    // insert data
    function insert($data)
    {
        $this->db2->insert($this->table, $data);
    }

    // insert data lokasi
    function insert_lokasi($data)
    {
      $this->db2->insert('lokasi', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db2->where($this->id, $id);
        $this->db2->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db2->where($this->id, $id);
        $this->db2->delete($this->table);
    }

}

/* End of file Pekerjaan_model.php */
/* Location: ./application/models/Pekerjaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-27 13:30:41 */
/* http://harviacode.com */
