<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    // get jumlah masing2 status
    function get_jumlah_status($id_lap)
    {
		$this->db->select('*');
		$this->db->from('pelaporan');
		$this->db->where('id_lap',$id_lap);		
		$jml_pelapor = $this->db->count_all_results(); //JUMLAH PELAPOR
		
		$this->db->select('*');
		$this->db->from('pelaporan p');
		$this->db->where('p.id_lap',$id_lap);
		$this->db->where('p.id_status',1); //belum lapor
		$this->db->join('skpd s', 's.id_skpd=p.id_skpd', 'left');		
		$this->db->join('status t', 't.id_status=p.id_status', 'left');
		$this->db->join('jabatan j', 'j.id_jab=p.id_jab', 'left');
		$this->db->order_by('p.id_pelaporan','desc'); 
		$query = $this->db->get();
		$jml_belum_lapor = $query->num_rows();  //JUMLAH status belum lapor
		$data_belum_lapor = $query->result(); //DATA STATUS BELUM LAPOR
		
		$this->db->select('*');
		$this->db->from('pelaporan p');		
		$this->db->where('p.id_status',2); //sudah lapor
		$this->db->where('p.id_lap',$id_lap);
		$this->db->or_where('p.id_status',3); // diminta perbaiki
		$this->db->where('p.id_lap',$id_lap);
		$this->db->or_where('p.id_status',5); //direvisi
		$this->db->where('p.id_lap',$id_lap);
		$this->db->or_where('p.id_status',7); //direvisi
		$this->db->where('p.id_lap',$id_lap);
		$this->db->join('skpd s', 's.id_skpd=p.id_skpd', 'left');		
		$this->db->join('status t', 't.id_status=p.id_status', 'left');
		$this->db->join('jabatan j', 'j.id_jab=p.id_jab', 'left');
		$this->db->order_by('p.tgl_upload','asc'); 
		$query = $this->db->get();
		$jml_sudah_lapor = $query->num_rows();  //JUMLAH status sudah, revisi dan perbaiki
		$data_sudah_lapor = $query->result(); //DATA STATUS sudah, revisi dan perbaiki
				
		$this->db->select('*');
		$this->db->from('pelaporan p');
		$this->db->where('p.id_lap',$id_lap);
		$this->db->where('p.id_status',4); //oke
		$this->db->join('skpd s', 's.id_skpd=p.id_skpd', 'left');		
		$this->db->join('status t', 't.id_status=p.id_status', 'left');
		$this->db->join('jabatan j', 'j.id_jab=p.id_jab', 'left');
		$this->db->order_by('p.id_skpd','asc'); 
		$query = $this->db->get();
		$jml_oke = $query->num_rows();  //JUMLAH status oke
		$data_oke = $query->result(); //DATA STATUS oke
		
		return array(
			'jml_belum_lapor' => $jml_belum_lapor,
			'jml_sudah_lapor' => $jml_sudah_lapor,
			'jml_oke' => $jml_oke,
			'data_belum_lapor' => $data_belum_lapor,
			'data_sudah_lapor' => $data_sudah_lapor,
			'data_oke' => $data_oke,
			'jml_pelapor' => $jml_pelapor,
		);
    }
	
}

/* End of file Disposisi_model.php */
/* Location: ./application/models/Disposisi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-11 10:14:44 */
/* http://harviacode.com */