<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Jabatan_model extends CI_Model
{

  public $table = 'jabatan';
  public $id = 'id_jab';
  public $order = 'DESC';

  function __construct()
  {
    parent::__construct();
  }

  // get all
  function get_all()
  {
    $this->db->select('*');
    $this->db->from('jabatan j');
    if (!$this->ion_auth->in_group('admin')) {
      $this->db->where('j.id_skpd',$this->session->userdata('id_skpd'));
    }
    $this->db->join('level_jabatan l', 'l.id_level=j.id_level', 'left');
    $this->db->join('skpd s', 's.id_skpd=j.id_skpd', 'left');
    $this->db->join('pegawai p', 'p.nip=j.nip', 'left');
    $this->db->join('users u', 'u.company=j.id_jab', 'left');
    $this->db->order_by('j.id_jab','desc');
    return $this->db->get()->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->select('*');
    $this->db->from('jabatan j');
    if (!$this->ion_auth->in_group('admin')) { //JIKA USER ADALAH BUKAN ADMIN ALIAS PENGELOLA KARNA USER BIASA SUDAH PASTI TIDAK BISA
      $this->db->where('j.id_skpd',$this->session->userdata('id_skpd'));
    }
    $this->db->where('j.id_jab',$id);
    $this->db->join('level_jabatan l', 'l.id_level=j.id_level', 'left');
    $this->db->join('skpd s', 's.id_skpd=j.id_skpd', 'left');
    $this->db->join('pegawai p', 'p.nip=j.nip', 'left');

    //$this->db->where($this->id, $id);
    return $this->db->get()->row();
  }

  // get data fk by id
  function get_fk_by_id($id)
  {
    // $fk1 = $this->db->where('id_jab', $id)->from('surat_masuk')->count_all_results();
    // $fk2 = $this->db->where('id_jab_t', $id)->from('disposisi')->count_all_results();
    $fk3 = $this->db->where('company', $id)->from('users')->count_all_results();
    // $fk = $fk1 + $fk2 +$fk3;
    $fk = $fk3;
    return $fk;
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

  function get_last_id(){
    $this->db->select('max(id_jab) as last_id');
    $current_id = $this->db->get('jabatan')->row()->last_id;
    return $current_id;
  }

}

/* End of file Jabatan_model.php */
/* Location: ./application/models/Jabatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-05 04:38:23 */
/* http://harviacode.com */
