<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Skpd_model extends CI_Model
{

    public $table = 'skpd';
    public $id = 'id_skpd';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*');
		$this->db->from('skpd s');
		$this->db->join('klasifikasi k', 'k.id_klasifikasi=s.id_klasifikasi', 'left');
    $this->db->where('nama_skpd <>','KDH WKDH')	;
		$this->db->order_by('s.id_skpd','asc');
		return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('*');
		$this->db->from('skpd s');
		$this->db->where('s.id_skpd', $id);
		$this->db->join('klasifikasi k', 'k.id_klasifikasi=s.id_klasifikasi', 'left');
		$this->db->order_by('s.id_skpd','desc');
        return $this->db->get()->row();
    }

	// get data fk by id
    function get_fk_by_id($id)
    {
        return $this->db->where('id_skpd', $id)->from('jabatan')->count_all_results();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_skpd', $q);
		$this->db->or_like('nama_skpd', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_skpd', $q);
		$this->db->or_like('nama_skpd', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Skpd_model.php */
/* Location: ./application/models/Skpd_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-05 05:46:16 */
/* http://harviacode.com */
