<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nilai_pagu_model extends CI_Model
{

    public $table = 'nilai_pagu';
    public $id = 'id_nilai_pagu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db3 = $this->load->database('db3',TRUE);
    }

    // get all
    function get_all()
    {
        $this->db3->order_by($this->id, $this->order);
        return $this->db3->get($this->table)->result();
    }

    // get all by id keg
    function get_by_idkeg($idkeg)
    {
        $this->db3->select('np.*,pp.*');
        $this->db3->from('nilai_pagu np');
        $this->db3->join('periode_pagu pp','pp.id_per_pagu=np.periode_pagu','left');
        $this->db3->where('np.kegiatan', $idkeg);
        return $this->db3->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db3->where($this->id, $id);
        return $this->db3->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db3->where('kegiatan', $data['kegiatan']);
        $this->db3->where('periode_pagu', $data['periode_pagu']);
        $num = $this->db3->get($this->table)->num_rows();
        if ($num > 0){
          $this->db3->where('kegiatan', $data['kegiatan']);
          $this->db3->where('periode_pagu', $data['periode_pagu']);
          $this->db3->update($this->table, $data);
        } else {
          $this->db3->insert($this->table, $data);
        }
    }

    // insert data total skpd
    function insert_total($total_data)
    {
        $this->db3->where('skpd', $total_data['skpd']);
        $this->db3->where('periode_pagu', $total_data['periode_pagu']);
        $num = $this->db3->get('pagu_skpd')->num_rows();
        if ($num > 0){
          $this->db3->where('skpd', $total_data['skpd']);
          $this->db3->where('periode_pagu', $total_data['periode_pagu']);
          $this->db3->update('pagu_skpd', $total_data);
        } else {
          $this->db3->insert('pagu_skpd', $total_data);
        }
    }

    // update data
    function update($id, $data)
    {
        $this->db3->where($this->id, $id);
        $this->db3->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db3->where($this->id, $id);
        $this->db3->delete($this->table);
    }

}

/* End of file Nilai_pagu_model.php */
/* Location: ./application/models/Nilai_pagu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-11 09:14:19 */
/* http://harviacode.com */
