<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Periode_setting_model extends CI_Model
{

  public $table = 'periode_setting';
  public $id = 'id_per_setting';
  public $order = 'DESC';

  function __construct()
  {
    parent::__construct();
    $this->db3 = $this->load->database('db3',TRUE);
  }

  // get all
  function get_all()
  {
    $db3 = $this->db3;
    $db3->select('ps.*,s.*,pp1.keterangan as keterangan1,pp2.keterangan as keterangan2,pp3.keterangan as keterangan3,pp4.keterangan as keterangan4,pp5.keterangan as keterangan5,pp6.keterangan as keterangan6,pp7.keterangan as keterangan7,pp8.keterangan as keterangan8,pp9.keterangan as keterangan9,pp10.keterangan as keterangan10,pp11.keterangan as keterangan11,pp12.keterangan as keterangan12');
    $db3->from('periode_setting ps');
    $db3->join('periode_pagu pp1','pp1.id_per_pagu=ps.b01','left');
    $db3->join('periode_pagu pp2','pp2.id_per_pagu=ps.b02','left');
    $db3->join('periode_pagu pp3','pp3.id_per_pagu=ps.b03','left');
    $db3->join('periode_pagu pp4','pp4.id_per_pagu=ps.b04','left');
    $db3->join('periode_pagu pp5','pp5.id_per_pagu=ps.b05','left');
    $db3->join('periode_pagu pp6','pp6.id_per_pagu=ps.b06','left');
    $db3->join('periode_pagu pp7','pp7.id_per_pagu=ps.b07','left');
    $db3->join('periode_pagu pp8','pp8.id_per_pagu=ps.b08','left');
    $db3->join('periode_pagu pp9','pp9.id_per_pagu=ps.b09','left');
    $db3->join('periode_pagu pp10','pp10.id_per_pagu=ps.b10','left');
    $db3->join('periode_pagu pp11','pp11.id_per_pagu=ps.b11','left');
    $db3->join('periode_pagu pp12','pp12.id_per_pagu=ps.b12','left');
    $db3->join('epiz_21636198_simolek.skpd s', 's.id_skpd=ps.skpd', 'left');
    $this->db3->order_by($this->id, $this->order);
    return $this->db3->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db3->where($this->id, $id);
    return $this->db3->get($this->table)->row();
  }

  // insert data
  function insert($data)
  {
    $this->db3->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db3->where($this->id, $id);
    $this->db3->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db3->where($this->id, $id);
    $this->db3->delete($this->table);
  }

}

/* End of file Periode_setting_model.php */
/* Location: ./application/models/Periode_setting_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-30 09:06:30 */
/* http://harviacode.com */
