<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Periode_pagu_model extends CI_Model
{

    public $table = 'periode_pagu';
    public $id = 'id_per_pagu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db3 = $this->load->database('db3',TRUE);
    }

    // get all
    function get_all()
    {
        $this->db3->order_by($this->id, $this->order);
        return $this->db3->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db3->where($this->id, $id);
        return $this->db3->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db3->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db3->where($this->id, $id);
        $this->db3->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db3->where($this->id, $id);
        $this->db3->delete($this->table);
    }

}

/* End of file Periode_pagu_model.php */
/* Location: ./application/models/Periode_pagu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-11 09:14:14 */
/* http://harviacode.com */
